### ISSUE TITLE
Taking without credit is frowned upon. Heavily.

### ISSUE THREAD

**Issue by UberGuidoZ** [CoAntics/FlipperZeroDB#5]

**Comment by UberGuidoZ** [comment]
Looking at the "contributors" it appears 2 are bot accounts, and a likely 3rd is @curiousqeorqe while the actual user is @XSxZR.

I doubt this reach-out will make a difference. The least you could do is keep it up to date... ¯\_(ツ)_/¯  Hopefully your follows stumble on the real one as there is a lot of good info they are missing out on.

**Comment by CoAntics** [comment]
Hi @uberGuidoZ 
This git was never ment be taken as a disrespect 
just to answer some
